import Head from "next/head";
import Link from "next/link";
import { api } from "@@/utils/api";
import { Button } from "@@/components/ui/button";
import { Textarea } from "@@/components/ui/textarea";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="flex w-1/2 flex-col items-center">
          <Textarea
            className="my-2 w-3/4"
            placeholder="Paste HTML document here..."
          />
          <Button className="my-2 w-1/3">I&lsquo;m A Button</Button>
        </div>
      </main>
    </>
  );
}
